const DATA={
"Robotics":{icon:"🤖",summary:"A structured robotics pathway covering electronics, programming, sensors, actuators and practical robotic systems.",modules:{Beginner:["Introduction to robotics and safety","Basic electronics and circuits","Arduino fundamentals and C/C++ basics","Sensors and actuators","Motors and motor drivers","Ultrasonic and IR sensing","Build a basic obstacle-avoiding robot"],Intermediate:["Microcontroller programming and structured code","Sensor integration and debugging","Motor control and robotics logic","Wireless communication concepts","ESP32 and connected robotics","Project planning, assembly and testing","Build an intermediate autonomous system"],Expert:["Advanced robotics architecture","ESP32-based systems and connectivity","IoT-enabled robotics","Control, communication and system integration","Advanced debugging and optimization","Prototype development and documentation","Capstone robotics project"]}},
"IoT":{icon:"🌐",summary:"A progressive IoT pathway from microcontrollers and sensors to networking, MQTT, cloud and connected systems.",modules:{Beginner:["IoT concepts and applications","Circuits and electronics basics","C programming foundations","Arduino and ESP32 basics","Sensors and data collection","Basic Wi-Fi connectivity","Build a connected sensor project"],Intermediate:["IoT networking concepts","MQTT and HTTP fundamentals","ESP32 projects","Sensor integration and data handling","Dashboards and device communication","Debugging and testing connected devices","Build an IoT monitoring system"],Expert:["Industrial IoT concepts","MQTT and secure communication","LoRaWAN and Zigbee overview","CoAP and HTTP","Cloud-connected architectures","Security and reliability","Build an advanced IIoT project"]}},
"Artificial Intelligence":{icon:"🧠",summary:"Build a foundation in AI concepts and practical intelligent applications.",modules:{Beginner:["What is AI?","Problem solving and intelligent systems","Data and patterns","AI applications","Basic Python concepts","Simple AI experiments","Mini project"],Intermediate:["AI workflows","Data preparation","Model concepts","Evaluation basics","Practical AI applications","Project development","Intermediate AI project"],Expert:["Advanced AI concepts","Model design and evaluation","AI system architecture","Responsible AI fundamentals","Project optimization","Research-oriented problem solving","Capstone project"]}},
"Machine Learning":{icon:"📊",summary:"Learn the foundations of machine learning, from data preparation to model development.",modules:{Beginner:["ML concepts","Data types and datasets","Features and labels","Basic Python workflow","Introductory models","Evaluation concepts","Mini project"],Intermediate:["Data preprocessing","Supervised learning","Unsupervised learning","Model evaluation","Feature engineering","Model comparison","Applied ML project"],Expert:["Advanced model concepts","Optimization","Model pipelines","Advanced evaluation","Deployment concepts","Experiment tracking","Capstone ML project"]}},
"Deep Learning":{icon:"⚡",summary:"Explore neural networks and deep-learning concepts through progressively advanced projects.",modules:{Beginner:["Deep learning overview","Neural network intuition","Data and tensors","Basic Python workflow","Simple neural networks","Training concepts","Mini project"],Intermediate:["Network architectures","Training and validation","Computer vision foundations","Model tuning","Transfer learning concepts","Experimentation","Applied deep learning project"],Expert:["Advanced architectures","Optimization techniques","Model evaluation","Deployment concepts","Research workflows","System design","Deep learning capstone"]}},
"Automation":{icon:"⚙️",summary:"Learn how sensors, controllers, actuators and logic combine to automate real-world tasks.",modules:{Beginner:["Automation concepts","Sensors and inputs","Controllers","Relays and actuators","Basic control logic","Safety and testing","Mini automation project"],Intermediate:["Advanced sensor integration","Control logic","ESP32 automation","Communication protocols","Dashboard and remote control","Debugging","Intermediate automation project"],Expert:["Industrial automation concepts","IIoT integration","Reliable control systems","Communication and security","System architecture","Optimization","Advanced automation capstone"]}}
};
const params=new URLSearchParams(location.search),course=params.get("course")||"Robotics",level=(params.get("level")||"Beginner").replace(/^./,c=>c.toUpperCase()),d=DATA[course]||DATA.Robotics;
const levels=["Beginner","Intermediate","Expert"],prereq=level==="Intermediate"?"Beginner":level==="Expert"?"Intermediate":null;
document.getElementById("course").innerHTML=`<div class="section-heading reveal is-visible"><span class="eyebrow">${d.icon} ${course.toUpperCase()}</span><h1 style="font-family:'Space Grotesk';font-size:clamp(42px,7vw,76px);margin:14px 0">${level} Level</h1><p>${d.summary}</p></div>
<div class="levels" style="margin-bottom:35px">${levels.map(l=>`<a class="btn ${l===level?"primary":"ghost"}" href="course.html?course=${encodeURIComponent(course)}&level=${l}">${l}</a>`).join("")}</div>
<div class="why-grid"><article class="why-item"><b>COURSE OVERVIEW</b><h3>What you'll learn</h3><p>${d.summary}</p></article><article class="why-item"><b>STRUCTURE</b><h3>Progressive learning</h3><p>Students move from concepts to guided practice and projects appropriate to the selected level.</p></article><article class="why-item"><b>PREREQUISITE</b><h3>${prereq?prereq+" recommended":"No prerequisite"}</h3><p>${prereq?`The ${level} pathway builds on the ${prereq} level. The registration form will check this before submission.`:"This level is the entry point for this pathway."}</p></article></div>
<section class="section" style="padding-left:0;padding-right:0"><div class="section-heading"><span class="eyebrow">CURRICULUM</span><h2>${course} — ${level}</h2></div><div class="why-grid">${d.modules[level].map((m,i)=>`<article class="why-item"><b>${String(i+1).padStart(2,"0")}</b><h3>${m}</h3><p>Guided learning, practical activities and project work.</p></article>`).join("")}</div></section>
<section class="cta-section reveal is-visible"><div><span class="eyebrow">READY?</span><h2>Register for ${course} — ${level}</h2><p>Registration collects student and parent details, prior experience and your preferred contact time. Our team will then contact you about schedule and payment.</p></div><a class="btn primary" href="register.html?course=${encodeURIComponent(course)}&level=${level}">Register Now →</a></section>`;
