const p=new URLSearchParams(location.search),course=p.get("course")||"Robotics",level=p.get("level")||"Beginner";
document.getElementById("courseTitle").textContent=`${course} — ${level}`;
document.querySelector('[name="course"]').value=course;document.querySelector('[name="level"]').value=level;
const prereq=level==="Intermediate"?"Beginner":level==="Expert"?"Intermediate":null;
const q=document.getElementById("prerequisite"),warn=document.getElementById("prereqWarning"),submit=document.getElementById("submitBtn"),exp=document.getElementById("experienceWrap");
if(!prereq){q.closest("label").hidden=true;document.getElementById("experienceWrap").hidden=true}else{
q.previousElementSibling.textContent=`Have you already completed the ${prereq}-level ${course} course on any platform?`;
q.addEventListener("change",()=>{const no=q.value==="No",yes=q.value==="Yes";if(no){warn.hidden=false;warn.innerHTML=`<strong>⚠️ ${prereq} level recommended</strong><br>We recommend completing the ${prereq}-level ${course} course before enrolling in ${level}. The ${level} curriculum builds on the foundation from the previous level. Direct entry may make it difficult to follow the learning structure and keep pace with other students.<br><br><a href="course.html?course=${encodeURIComponent(course)}&level=${prereq}">View ${prereq} Course →</a>`}else warn.hidden=true;exp.hidden=!yes;submit.disabled=!yes&&no;submit.style.opacity=no?".5":"1";});
}
const date=document.getElementById("contactDate"),today=new Date();date.min=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);
let googleUser=null;
function initGoogle(){if(!window.google||!window.BOTNEST_CONFIG)return;const id=BOTNEST_CONFIG.GOOGLE_CLIENT_ID;if(!id||id.startsWith("YOUR_"))return;google.accounts.id.initialize({client_id:id,callback:cred=>{googleUser=cred;try{const payload=JSON.parse(atob(cred.credential.split(".")[1].replace(/-/g,"+").replace(/_/g,"/")));document.getElementById("email").value=payload.email||"";document.querySelector('[name="parentName"]').value=payload.name||"";document.querySelector('[name="googleSub"]').value=payload.sub||"";document.getElementById("authStatus").textContent=`Signed in as ${payload.email}`;}catch(e){}}});google.accounts.id.renderButton(document.getElementById("googleButton"),{theme:"outline",size:"large",shape:"pill",text:"continue_with"});}
const gs=document.createElement("script");gs.src="https://accounts.google.com/gsi/client";gs.async=true;gs.defer=true;gs.onload=initGoogle;document.head.appendChild(gs);
document.getElementById("regForm").addEventListener("submit",async e=>{e.preventDefault();if(prereq&&q.value==="No"){return}const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries());data.timestamp=new Date().toISOString();const status=document.getElementById("formStatus");submit.disabled=true;status.textContent="Submitting your registration…";const url=BOTNEST_CONFIG.APPS_SCRIPT_URL;if(!url||url.startsWith("YOUR_")){status.textContent="Backend is not connected yet. Complete the Apps Script setup in README-SETUP.md.";submit.disabled=false;return}try{await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)});document.getElementById("regForm").hidden=true;document.getElementById("authBox").hidden=true;document.getElementById("success").hidden=false;document.getElementById("successText").textContent=`We have received your ${level}-level ${course} registration. Our team will contact you on ${data.contactDate} at ${data.contactTime}, as requested, regarding the course schedule, payment and next steps.`;window.scrollTo({top:0,behavior:"smooth"});}catch(err){status.textContent="We couldn't submit the form. Please try again or contact us on WhatsApp.";submit.disabled=false}});
